version: "2"

services:

  application:
    image: tianon/true
    volumes:
      - .:/var/www/application

  bg-sync:
      image: cweagans/bg-sync
      volumes:
        - .:/source
      volumes_from:
        - application
      environment:
        - SYNC_DESTINATION=/var/www/application
        - SYNC_MAX_INOTIFY_WATCHES=40000
        - SYNC_VERBOSE=1
      privileged: true
#
#  mysql:
#    image: mysql:5.6
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: 123
#      MYSQL_DATABASE: symfony

  nginx:
    image: nginx:1.9
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - php
    ports:
      - "80:80"
    volumes_from:
      - application
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: pcodk/php7
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
#      - mysql
      - mailhog
    volumes_from:
      - application
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  devtools:
    image: pcodk/devtools
    volumes_from:
      - application

  phpcs:
    image: pcodk/phpcs
    volumes_from:
      - application